### ISSUE TITLE
Deleting a Group doesn't trigger CastListener's remove_cast

### ISSUE THREAD

**Issue by mainTAP** [home-assistant-libs/pychromecast#473]
Dear team,
It seems that when a casting speaker group is deleted, the remove_cast() is not triggered by CastListener, and the group stays in the browser's device list.
This can be reproduced by running the included discovery_example.py using the latest pychromecast 9.0.0 , and deleting a speaker group using the google home app.
Thank you very much for this great library.

**Comment by emontnemery** [comment]
I think this may be a regression in 9.0.0 caused by the `HostBrowser` which will fail toprune groups if the last known `elected_leader` is offline.

Could you verify it works on pychromecast version 8?

**Comment by mainTAP** [comment]
Thank you, yes, in version 8.1.2 the remove callback is triggered.

**Comment by emontnemery** [comment]
Can you give the attempted fix in #475 a try?

**Comment by mainTAP** [comment]
Thank you very much, it seems to be working.
btw, is the empty cast_info of the deleted group ever going to be removed from the browser.devices or it stays there for some reason?

**Comment by emontnemery** [comment]
Great, thanks for confirming!

By not removing the cast_info although it has no known services, a running socket_client will pick up a new service in the cast_info's services set, if there ever is one.

The empty set in the cast_info stays there because we don't know that the group has been actively deleted, we just know that the cast which was the last known elected leader no longer is leading the group.

If there is a way to know that a group has been permanently removed, we could purge it from browser.devices.
