### ISSUE TITLE
Play livestreams with least delay possible

### ISSUE THREAD

**Issue by Silun** [home-assistant-libs/pychromecast#479]
I am trying to play an audio livestream with the least delay possible over a stereo pair of cast-enabled speakers. I saw a similar issue, https://github.com/home-assistant-libs/pychromecast/issues/356, that had people saying there was no real way to just not buffer unnecessarily. Basically, it looks like the way to get the lowest amount of delay in a livestream would be something like this, which is just blasting the receiver with requests until he starts.

```python
def run_asap(receiver, interval, blast_duration):
    count = int(blast_duration/interval)
    for i in range(count):
        time.sleep(interval)
        receiver.play()
```

And use it like so:
```python
mc.play_media('some_local_network_file', 'audio/wav', title='TITLE', stream_type='LIVE')
mc.block_until_active()
run_asap(mc, 0.1, 3)
```

I get about ~1.5 seconds delay, sometimes less and sometimes more using this method, it is not 100% consistent. It really doesn't feel like that is what I should be doing, though. Is there really no better way?

**Comment by emontnemery** [comment]
I don't think this issue adds anything which is not already covered by #356?

The problem is the buffering algorithm in the "default media receiver" app, which we can't do anything about.
Workarounds are spamming the play command, as you suggest here and as has already been suggested in #356, and/or using another app than "default media receiver".
