### ISSUE TITLE
Feature Request: disableIdleTimeout flag

### ISSUE THREAD

**Issue by GSzabados** [home-assistant-libs/pychromecast#519]
As it seems to be the new Fuchsia OS enforces a 30 seconds timeout for casted webpages as it goes into "ambient" mode, what used to be 15-30 minutes.

Would it be possible to implement the disableIdleTimeout flag, if it is working, as many other options were incorrect from Google's documentation?

Reference docs here:

https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.CastReceiverOptions#disableIdleTimeout

So user comments here and below regarding the new 30 seconds timeout:

https://community.home-assistant.io/t/using-catt/130332/398

**Comment by jonaseymour** [comment]
> But looking at what you have referenced from Home Assitant Cast, I am a bit confused, because people using Home Assistant Cast as well has reported the same issue. So, I have doubts now, that would this solve it.

Yes, I tried HA Cast to see if it fixed the issue and I still experienced a 30s timeout.

If it doesn't work, is it possible to try specifying the [maxInactivity](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.CastReceiverOptions#maxInactivity) instead, and see if that works?

**Comment by danielbcook** [comment]
> This needs to be set on a per app basis, and it's done for the Home Assistant app:
> https://github.com/home-assistant/frontend/blob/dev/cast/src/receiver/entrypoint.ts#L61
> Can you give some background on the use case where the 30s timeout affects you?

The use case for most people reporting this Dashcast problem on Home Assistant is that they're using a Nest Hub as a smart home dashboard in "kiosk" mode. In my case I previously located my Nest in the kitchen for the whole family to use, but once it started going to Ambient mode after 30 seconds the dashboard significantly lost its value. Right now, at best, I get a roughly 45/45/10 duty cycle between seeing the relevant dashboard (max 30 sec), the Ambient mode clock face, and the transitions in between.

**Comment by jonaseymour** [comment]
Just touching base whether there is anything that can be tested on this?

In the meantime, I have started a topic on the [nest community forum](https://www.googlenestcommunity.com/t5/Speakers-and-Displays/Request-for-inactivity-timeout-to-be-reverted-back-to-10-minutes/m-p/14650#M3463) for anyone that wants to add support.

**Comment by emontnemery** [comment]
The Home Assistant app used for casting a Lovelace view already sets the `disableIdleTimeout` flag.
The problem is that Fuchsia OS doesn't respect the flag.

We've reached out to Google who confirm that they can reproduce the problem, and that the technical reason is that the app reports that it's being "idle". To my understanding, the idle status is because the app is not playing media, which is intentional when showing a Lovelace view.

It's not clear yet if this is a problem in Home Assistant's chrome app which we can fixed there or a problem in Fuchsia.

Whichever the case, I don't think this can be solved in pychromecast.
There's an issue on Home Assistant: https://github.com/home-assistant/core/issues/53882

**Comment by emontnemery** [comment]
@jonaseymour the Home Assistant app already sets `maxInactivity`: https://github.com/home-assistant/frontend/blob/49494c572b1f235070cf43a0243ba50cdd810c28/cast/src/receiver/entrypoint.ts#L80

**Comment by jonaseymour** [comment]
Thanks @emontnemery Appreciate the work trying to figure it out.
