### ISSUE TITLE
Unable to find documentation

### ISSUE THREAD

**Issue by Silun** [home-assistant-libs/pychromecast#530]
Hello,
I have used pychromecast to stream audio to my Chromecast Audios, but there is a very high delay (~10 seconds) even when the stream type is set to `LIVE`. I was wondering what the recommended way to minimize delay is, so far I have come up with just sending the `play()` command again and again and again really quickly, to make it start sooner. That leads to there being some stuttering later on though, and it's just ugly.

**So I was trying to find the documentation, to look some other things up as well, and I just cannot find it.** Maybe I am just blind, but I have been looking for a while and can't find it even on google. Does it exist? Are there more best practices or examples other than the readme on github?

For example, where should I look for info on something like displaying all Chromecasts on my network in order to select a target, since `get_listed_chromecasts()` returns an empty list if no `friendly_names=[name]` is specified? I know that `discovery.discover_chromecasts()` returns a lot of stuff, but I am not sure how to handle that.

**Comment by emontnemery** [comment]
The high delay is due to the behavior of Google's "default media receiver" app which is used to play media unless an app is specified instead. As you correctly state, the `LIVE` does not make a big difference, if any. This is not something we can control from pychromecast. What you can do is to use another app, the BubbleUPNP seems to do a more aggressive buffering and thus starts playing faster.

The `examples/discovery_example.py` shows how to build an always up to date list of chromecasts on the network, combine that with one of the player examples and you should be good.

A PR on the documentation, or a new example script, would be most welcome!
