### ISSUE TITLE
BBC Sounds conroller stopped working

### ISSUE THREAD

**Issue by dunxd** [home-assistant-libs/pychromecast#752]
I noticed that my Home Assistant chrome cast scripts to play various BBC radio stations stopped working a couple of weeks ago.  I found [an issue in Home Assistant core](https://github.com/home-assistant/core/issues/101151) about this that included some workarounds that allow me to replace my scripts for the moment.

I thought I'd take a look to see if it is possible to get the bbcsounds app working again, and found my way here.

I then following [the instructions in README.md for exploring a namespace](https://github.com/home-assistant-libs/pychromecast#exploring-existing-namespaces) to see if I could figure out if things had changed with the Sounds controller - and I think I found the issue.  BBC now requires a sign in to play stations through the Sounds website. I didn't try this previously, but suspect it wasn't required until recently. I couldn't find any JSON in the SOCKET events - it looks like things may now be encrypted.  If that is the case, for pychromecast to support BBC Sounds it would need to be updated to allow sending credentials and decrypting.  I'm not 100% sure about this - it might make more sense to whoever wrote the BBC Sounds controller originally.

**Comment by blawford** [comment]
Hello. I have raised a PR to fix this #753.

The issue was just that BBC Sounds have changed their app_id, when I cast a radio station using my voice I get:
<img src="https://github.com/home-assistant-libs/pychromecast/assets/21213764/85533b9d-d0b1-41b3-bbbd-abc989582512" width=50% height=50%>

Whereas running through this integration:
<img src="https://github.com/home-assistant-libs/pychromecast/assets/21213764/e7afc94d-e97b-4d76-a64c-ec3abc0b85a2" width=50% height=50%>

**Comment by dunxd** [comment]
That's great to hear, and a relatively quick fix (assuming PRs are being handled for this repo).

I did read [on a manufacturer site](https://community.naimaudio.com/t/bbc-radio-will-mu-so-support-hls-dash/25993/3)  that BBC are going to require a license agreement to distribute HLS streams at some point in the future. At that point will it be necessary to have a BBC Sounds integration that allows individual login, similar to the Spotify integration?

**Comment by emontnemery** [comment]
Fixed by #753
